### PR TITLE
Set displayName

### PR DESCRIPTION
**Pull request by davidjbradshaw**
Just worked out how to do this.

Screenshot 2023-03-02 at 14 16 32

### CODE REVIEW

**Comment by cr3ative** [comment]
oh hell yea

**Comment by cr3ative** [comment]
`> homebridge-apcaccess@1.0.1 ` published.

**Comment by cr3ative** [comment]
image

Maybe we can update this to "Homebridge APC Access" next release because this is making my eye twitch. The redundancy is awful, but I feel the need to conform :D

**Comment by davidjbradshaw** [comment]
I submitted the same PR to every plugin I use. It looks much nice without the word homebridge everywhere.

**Comment by davidjbradshaw** [comment]
Screenshot 2023-03-03 at 09 27 37

**Comment by cr3ative** [comment]
Ha! Beautiful. Okay, as-is!

**Comment by davidjbradshaw** [comment]
If you have a moment it would be good to make PRs on all of the plugins you use. I just edited the `package.json` file on the install plugins on my rPi to get the screen shot, and then copied the added line and pasted it into the GitHub file edit screen to create the PR. Takes a couple of minutes for each one.

**Pull request merged**
